ROOTPWA-Maintainers/ROOTPWA

src/pwafit.cc

For some reason, the start values in pwafit for the minimizer were always
positive. Fix this by multiplying the seed value with -1. 50% of the time.

src: Fix start values in pwafit.

---

src/fitResult.cc

Fix the evidence calculation for the case of large covariance matrices (i.e.
several hundred parameters). Because of numerical limitations, the determinant
of the covariance matrix could become infinite, ruining the evidence
calculation. Fix this by calculating the eigenvalues of the covariance matrix
and adding up the logarithms of them which could still yield a sensible number.

src: Fix the evidence calculation for some cases.

---

amplitude/waveDescription.cc

Add the const-width Breit-Wigner function to the waveDescription, so that it
can actually be used in the keyfiles.

amplitude: Add const width Breit-Wigner.

---

src/pwaLikelihood.cc

Fix a bug in pwaLikelihood::readDecayAmplitude, where the array containing the
decay amplitudes was resized every time a new amplitude file was read in, while
slowed down the initial loading of amplitudes by some order of magnitudes.
While doing that, also finally fix the bug that the firstWave boolean was never
set to false so the consistency in terms of number of events in the amplitude
files was never properly checked as was intended.

src: Fix a bug in pwaLikelihood's readDecayAmplitudes.

---

partialWaveFit/addIntegralsToFitResult.cc
partialWaveFit/fitResult.cc
partialWaveFit/partialWaveFitHelper.cc
partialWaveFit/partialWaveFitHelper.h
partialWaveFit/pwaLikelihood.cc
partialWaveFit/pwaLikelihood.h

Fix issues #25 and #31.
Set the spin-density matrix elements to 0 for different reflectivities.
Set the entries in both norm matrices to 0 for different reflectivities mimicking the behaviour in the likelihood.
Properly split accepted norm matrix when calculating the evidence for fits with thresholds and ranks.

Fix issues around normalization matrices

---

CMakeLists.txt
README.md
cmakeModules/FindBAT.cmake
cmakeModules/FindROOT.cmake
compileBoostLibraries.sh
decayAmplitude/waveDescription.h
nlopt/pwaNloptFit.cc
partialWaveFit/5piMassDep.conf
partialWaveFit/calcCovMatrixForFitResult.cc
partialWaveFit/eigenvectorLikelihoodSlices.cc
partialWaveFit/partialWaveFitHelper.h
partialWaveFit/pwafit.cc
resonanceFit/CMakeLists.txt
resonanceFit/massDepFit.cc
resonanceFit/massDepFit.h
resonanceFit/massDepFitCache.h
resonanceFit/massDepFitComponents.cc
resonanceFit/massDepFitComponents.h
resonanceFit/massDepFitFsmd.cc
resonanceFit/massDepFitFsmd.h
resonanceFit/massDepFitFunction.cc
resonanceFit/massDepFitModel.h
resonanceFit/massDepFitParameters.h
resonanceFit/pwaMassFit.cc
utilities/CMakeLists.txt
utilities/environment.h.in
utilities/reportingUtilsEnvironment.cc

* Fix building with 'Apple LLVM 6.1.0' (Xcode 6.3):
* ignore warnings concerning ignored qualifiers while building the ROOT dictionaries (for ROOTv5 only)
* test whether the compiler understands thread_local (independent from using -std=c++11) because Apple does not support thread_local yet
* remove one test and definition not used anymore
* add BAT and NLopt to 'printLibraryInfo'
* add a function to the partialWaveFitHelper to extract Eigenvalues and -vectors from covariance and Hessian matrices taking into account fixed parameters, use this across the code; enable 'eigenvectorLikelihoodSlices' to (properly; i.e. no bogus plots for the last eigenvalues) work with fixed parameters
* draw parabolas in 'eigenvectorLikelihoodSlices'
* clean the code reading and writing the configuration file …

Various fixes and improvements

---

nlopt/pwaNloptFit.cc
src/pwaLikelihood.cc
src/pwaLikelihood.h
src/pwafit.cc

Make the width of the half-Cauchy prior changeable at runtime by making it a
standard member variable of the pwaLikelihood (as opposed to a const static
one) and adding a getter and setter for it. Also introduce a new command line
option in pwaNloptFit.cc which allows to set the prior width.

src: Make width of half-Cauchy prior settable.

---

nlopt/pwaNloptFit.cc
src/pwaLikelihood.cc
src/pwaLikelihood.h
src/pwafit.cc

Make the width of the half-Cauchy prior changeable at runtime by making it a
standard member variable of the pwaLikelihood (as opposed to a const static
one) and adding a getter and setter for it. Also introduce a new command line
option in pwaNloptFit.cc which allows to set the prior width.
This is a re-opening of pull request #79, which was inadvertently merged and then force-un-merged. It contains all the changes mentioned in the discussion there.

Custom cauchy width

---

decayAmplitude/waveDescription.cc
decayAmplitude/waveDescription.h
resonanceFit/massDepFitFsmd.cc

* fix the management of the _key pointer in the waveDescription, was not properly cleared and copied
* (potentially) fix parameter managment for the final-state mass-dependence for ROOT 6.04 by using the parameter name instead of the parameter index

Fix small issues in waveDescription and resonanceFit

---

relativisticAmpCorrections/TJSS.cc

There were two other instances where abs was used on long variables, change
these to labs as well.

relampl: Also use labs instead of abs elsewhere.

---

decayAmplitude/isobarAmplitude.cc
decayAmplitude/phaseSpaceIntegral.cc
decayAmplitude/waveDescription.cc
partialWaveFit/pwaLikelihood.cc
resonanceFit/massDepFitComponents.cc

Fix the values calculated by the `phaseSpaceIntegral` class. The volume of the integration was taken into account twice, once in the normalization of the `S_U_CHUNG` weight, and once explicitly in the calculation this class. Now only use the one from the normalization.
Also issue #91 is partially fixed. If the two Lorentz-vectors of beam and X are equal and X is at rest (a small variation is allowed), the boost matrix, which is basically the unit matrix except for the small allowed variation, is returned. The boost is also performed if X is not at rest, however, then a warning is printed.
The effects of those two corrections are depicted here:
Also fix a couple of smaller stuff:
* the copy and assignment constructors of the `waveDescription` should only parse the key file content, if they …

Fix phaseSpaceIntegral and small stuff

---

decayAmplitude/ampIntegralMatrix.cc
decayAmplitude/createGraphDiagram.cc
generators/weightEvents.cc
legacy/calcAmplitudes.cc
legacy/calcIntegrals.cc
legacy/pwaNloptFit.cc
legacy/pwafit.cc
legacy/pyInterface/package/_calcAmplitudes.py
pyInterface/CMakeLists.txt
pyInterface/amplitudeBenchmark.py
pyInterface/compareAmplitudeFiles.py
pyInterface/genPseudoData.py
pyInterface/genpw.py
pyInterface/integralBenchmark.py
pyInterface/package/utils/_printingUtils.py
pyInterface/partialWaveFit/partialWaveFitHelper_py.cc
pyInterface/partialWaveFit/partialWaveFitHelper_py.h
pyInterface/plotAngles.py
pyInterface/rootPwaPy.cc
pyInterface/rootpwa.config
pyInterface/testFileManager.py
pyInterface/userInterface/calcAmplitudes.py
pyInterface/userInterface/calcIntegrals.py
pyInterface/userInterface/pwaFit.py
pyInterface/userInterface/pwaNloptFit.py
resonanceFit/massDepFitComponents.cc
storageFormats/convertEventFile.py
storageFormats/printMetadata.py

* continue to remove the old binary amplitude file format and change the ROOT format over to using metadata
* change a couple of comments
* remove the option to read binary amplitude files and ASCII integral matrices from `weightEvents`, use `amplitudeMetadata` to get the tree containing the amplitudes
* new wave naming scheme in
* `weightEvents`
* `genPseudoData.py` (exporting `partialWaveFitHelper::getReflectivity` for this)
* move the initialization of `stdoutisatty` and `stderrisatty` so that it is done while `import pyRootPwa` so that not every script needs to set this
* phase-space integral used in the mass dependent fit now is the real phase-space integral without the factor `mass` that Dima includes
* correct various error messages and warnings

Various things

---

pyInterface/utilities/physUtils_py.cc
utilities/physUtils.hpp

function added to calculate tprime (t') from kinematic variables as
TLorentzVectors. Implement this as method for the decayTopology as well
as in the python bindings to be called from python

add tprime function from kinematic variables

---

pyInterface/storageFormats/amplitudeMetadata_py.cc

Fix a bug in the python bindings for amplitudeMetadata, which prevented the
retrieval of the event metadata information.

pyInterface: Fix a bug in amplitudeMetadata_py.

---

pyInterface/genPseudoData.py

Remove command line argument for keyfiles, since the filemanager takes care of
that. Change random seed default to 0.

pyInterface: small changes to genPseudoData

---

decayAmplitude/massDependence.h
decayAmplitude/waveDescription.cc
decayAmplitude/waveDescription.h
pyInterface/decayAmplitude/waveDescription_py.cc
pyInterface/testPyRootPwa.py

* use same mass dependence names when writing and reading keyfile
* allow to store `flatMassDependence` for an isobar decay
* Python default value in `waveDescription::writeKeyFile` is same as in C++

Fix a couple of things concerning mass dependencies and keyfiles

---

partialWaveFit/pwaLikelihood.cc

Fix the second derivative of the Cauchy prior, this also fixes negative
eigenvalues in the Hesse matrix that appeared when using the Cauchy
prior.

partialWaveFit: fix second derivative of Cauchy prior.

---

partialWaveFit/fitResult.cc
partialWaveFit/fitResult.h
plotScripts/plotGui.C
pyInterface/partialWaveFit/fitResult_py.cc

Clean up the business with the pattern matching for wave names in the fit
result by removing some ancient lines, making the escaping functions available
in python and adjusting plotGui accordingly. This probably breaks some of the
root scripts using the fit result, but all the compiled code seems to continue
to work.

partialWaveFit: Clean up wave name escaping.

---

pyInterface/package/utils/_fitTreeUtils.py
pyInterface/partialWaveFit/fitResult_py.cc

Add a python binding for a fit result function which was missed and make rootpwa compile again in a python 2.6 environment.

Fix things.

---

generators/weightEvents.cc
partialWaveFit/fitResult.cc
partialWaveFit/fitResult.h
pyInterface/partialWaveFit/fitResult_py.cc
resonanceFit/massDepFit.cc

Change all the TStrings appearing in the interface of fitResult to std::string
and adapt all affected places accordingly.

partialWaveFit: Remove TString from interface.

---

pyInterface/decayAmplitude/ampIntegralMatrix_py.cc
pyInterface/partialWaveFit/fitResult_py.cc
pyInterface/pyUtils/rootConverters_py.cc
pyInterface/pyUtils/rootConverters_py.h
pyInterface/storageFormats/amplitudeMetadata_py.cc
pyInterface/storageFormats/amplitudeTreeLeaf_py.cc

Fix some problems in the python bindings for the amplitudeTreeLeaf concerning
writing and reading from a root tree, adapt the branch-creating function to
utilize the possibility to set bufsize and splitlevel and add a function which
was missing to the bindings of the amplitudeMetadata. Remove a tree-related
function from the bindings of the ampIntegralMatrix, as these classes are not
stored in trees.

pyInterface: Fix several root related problems.

---

pyInterface/partialWaveFit/pwaLikelihood_py.cc

add a second addNormIntegral and addAccIntegral python wrapper
to also support boost wrapped ampIntegralMatrices alongside with
the ROOT wrapped ones

pwaLikelihood: support boost and ROOT wrappers

---

travisCI/install-cmake.sh

`wget` apparently does not understand the new certificate use for the `Cmake` servers, so use `curl` instead.
The error message was
```
ERROR: no certificate subject alternative name matches
requested host name `cmake.org'.
```

Try to get travis to work again.

---

resonanceFit/massDepFit.cc
resonanceFit/massDepFit.h
resonanceFit/massDepFitComponents.cc
resonanceFit/massDepFitComponents.h
resonanceFit/massDepFitMinimizerRoot.cc
resonanceFit/pwaMassFit.cc

* Fix a bug while using branchings, the cache was not invalidated correctly. Fits using only couplings were not affected.
* Fix a bug while writing the result of a fit using branchings to the output file. Fits using only couplings were not affected.
* No longer automatically free the couplings, they have to be explicitly freed using the `freeparameters` option. The default if the `freeparameters` option is not in the option file is to free the couplings.
* Create the graphs of the fit result with an adjustable granularity, no longer use the smooth line (ROOT TGraph draw option `C`) but a simple polyline (`L`). The default is to only have points at the mass bin centers, with the command line option `-F` the number of points can be increased (default value 1).
* In case multiple bins are …

Fix and improve resonance fit.

---

resonanceFit/CMakeLists.txt
resonanceFit/massDepFit.cc

Apparently the same thing as fixed in 557f0b4cbbfb53507a90a980b06b9d5f9f80ceca now for a different source file.

Try fixing compilation in travis

---

decayAmplitude/isobarAmplitude.cc
decayAmplitude/isobarDecayTopology.h
pyInterface/decayAmplitude/isobarAmplitude_py.cc

Fix the disabling of the Bose- and Isospin symmetrization mechanisms, which
were just left with no amplitude terms at all until now.

Fix disabling of symmetrizations.

---

.gitignore
decayAmplitude/isobarDecayTopology.cc

Partial waves with more than one isospin group (e.g. K- pi- pi+) lead to too much
isospin terms in the isospin symmetrization due to a wrong handling of groups.

isobarDecayTopology: Fix wrong isospin symmetrization with > 1 group

---

partialWaveFit/fitResult.cc

In addition to a crash while calculating the errors for a rank-2 fit (#149), there is a much more serious bug in `fitResult::intensityErr`. The function call to `normIntegralForProdAmp` should not use the indices of the `prodAmpIndices` array `i` and `j`, but the content of that array at the respective positions. Patterns that match a single wave should be fine. Patterns that match multiple waves probably return a wrong error for all patterns that did not result in a continuous sequences of production amplitude indices and were not starting from production amplitude index zero (realistically that is all except the '.*' pattern).
The actual impact of this bug is fortunately hardly visible in the plots I compared so far.
Replaces #149.
Fixes #140.
Fixes #60.

Fix calculation of intensity errors

---

pyInterface/package/utils/_waveDescThresUtils.py

The python function 'getWaveDescThresFromWaveList' should check whether
a line read from the wavelist can be split into either one or two parts,
not whether the split array is either '1' or '2'. This was broken by commit
71a39d39057ddc47868cbba46cb12868c9806cb5,

pyInterface: fix 'getWaveDescThresFromWaveList'

---

decayAmplitude/rootPwaAmpLinkDef.h
pyInterface/package/_integrals.py
pyInterface/package/_integralsOnTheFly.py

add dictionaries for all subclasses.
existing amplitudeHash not fatal, since in special cases
the same hases can appear several times.

ampIntegralMatrixMetadata: small patch

---

userAnalysisWorkspace/3pi.--+/keyfiles/GenerateKeyfiles.sh
userAnalysisWorkspace/3pi.-00/keyfiles/GenerateKeyfiles.sh
userAnalysisWorkspace/pi_2eta.-00/keyfiles/GenerateKeyfiles.sh

* fix behaviour if `WAVESET_FILES` contains the full paths
* allow to specify template keyfile with `TEMPLATE_KEY_FILES` environment variable, which no longer requires the template keyfiles to be present in the current directory

Fix 'GenerateKeyfiles.sh' scripts

---

pyInterface/userInterface/pwaFit.py
pyInterface/userInterface/pwaNloptFit.py

Add a '--noAcceptance' option to 'pwaFit.py' and 'pwaNloptFit.py' which
allows to perform fits without taking the acceptance into account.

pyInterface: add option to fit without acceptance correction

---

CMakeLists.txt
cmakeModules/FindBAT.cmake

Require at least BAT version 1.0. There was a massive interface change
with this version so we cannot support earlier and later versions at the
same time, so we will only support the new versions.
Remove leading and trailing whitespaces from BAT's special linker flags.

buildSystem: linker flags and new version for BAT

---

decayAmplitude/phaseSpaceIntegral.cc
decayAmplitude/phaseSpaceIntegral.h
pyInterface/decayAmplitude/phaseSpaceIntegral_py.cc
pyInterface/genPseudoData.py
pyInterface/package/_config.py
pyInterface/rootpwa.config
pyInterface/userInterface/calcAmplitudes.py

Finally add the possibility to customize the phase space integral functionality
(which enables the relativistic Breit-Wigner mass dependence functions if the
daughters of the decay are not stable themselves) in the rootpwa.config file.

decayAmplitude: Add phase space options.

---

pyInterface/package/_likelihood.py
pyInterface/userInterface/calcCovMatrixForFitResult.py
pyInterface/userInterface/eigenvectorLikelihoodSlices.py
pyInterface/userInterface/likelihoodPointCalculator.py

Fix the pylint tests for the three python scripts which have been broken by the
recent revision of the file manager and the on-the-fly binning. These fixes are
rather ugly and there is a significant amount of code duplication, but these
scripts need to be revisited and revised anyway when the automatic integral
merging for the fitting is implemented.

tests: Fix the pylint tests for the scripts.

---

partialWaveFit/fitResult.cc

**Check before merging!**
The two entries of the Jacobian matrix of the phase corresponding to the derivative with respect to real and imaginary part of the spin-density matrix were swapped.

partialWaveFit: fix 'fitResult::phaseErr'

---

partialWaveFit/fitResult.cc

This includes #166.
Fix the calculation of the error of an intensity if the full integral matrix was stored. The effect of this bug was somewhat reduced by setting entries corresponding to waves with different reflectivities to zero in the matrix (about a year ago). Now properly fix this also for older fit results.
Also fix a small issue without any effect concerning the `_normIntIndexMap`.

Fix calculation of intensity error

---

pyInterface/module/utils/_waveDescThresUtils.py

Remove a no longer required import statement from the '_waveDescThresUtils.py' file.
Broken after merging #172.

pyInterface: fix pylint test

---

highLevelInterface/pwaFit.cc
highLevelInterface/pwaNloptFit.cc
partialWaveFit/fitResult.cc
partialWaveFit/fitResult.h
partialWaveFit/partialWaveFitHelper.cc
partialWaveFit/partialWaveFitHelper.h
partialWaveFit/pwaLikelihood.cc
partialWaveFit/pwaLikelihood.h
pyInterface/bindings/partialWaveFit/fitResult_py.cc
pyInterface/bindings/partialWaveFit/pwaLikelihood_py.cc
pyInterface/bindings/pyUtils/stlContainers_py.cc
pyInterface/module/_likelihood.py
pyInterface/scripts/calcCovMatrixForFitResult.py
pyInterface/scripts/eigenvectorLikelihoodSlices.py
pyInterface/scripts/likelihoodPointCalculator.py

* no longer store the names of production amplitudes in the fit result, instead store a wave index and a rank for each production amplitude, unfortunately this broke `boost::python` as there were too many arguments to the `fitResult::fill` method, so now do not pass individual vectors, but tuples of vectors
* add a new `spinDensityMatrixTimesAmplitudeMatrix` method to calculate the weights for a subset of waves in one central place, and not have to implement this over and over again
* some cleaning of the code
For my test cases old fit results are still read correctly (after changes to the ROOT I/O rules).

Update fit result

---

pyInterface/scripts/printMetadata.py

Do not require that 'printMetadata' is called with an argument
specifying which amplitude to print, but loop over the keys of the ROOT
file, and print all amplitude metadata objects that are found. This
covers the typical case of one amplitude per file, but should also be
working if multiple amplitudes are stored in the same file.

pyInterface: search for amplitude metadata in 'printMetadata'

---

pyInterface/module/_fileManager.py
pyInterface/scripts/plotAngles.py

Directly loop over dictionaries instead of instead of calling 'keys()'. This fixes pylint check C0201 (consider-iterating-dictionary).

pyInterface: fix for new pylint versions

---

pyInterface/CMakeLists.txt

Do not install the 'pwaNloptFit' Python script and do not add a test for this script if ROOTPWA is compiled without support for NLopt.

buildSystem: 'pwaNloptFit' without NLopt library

---

cmakeModules/FindNLopt.cmake

Fix the name of the header file searched when the system library should
be used (i.e., the NLOPT environment variable is not set). The name jad
the wrong capitalization and we are actually interested in the header
file for C++, not pure C.

buildSystem: fix NLopt header when using system library

---

CMakeLists.txt
cmakeModules/FindPYLINT.cmake
pyInterface/CMakeLists.txt

Require at least version 1.5.5 of pylint and only add the tests if at least this version was found. Older versions might be fine but I cannot test starting from which version they work.

Check pylint version

---

pyInterface/module/_integralsOnTheFly.py

The `continue` statement only affected the loop over kinematic variables, not the event loop

_integralsOnTheFly.py: Small bug fix

---

partialWaveFit/complexMatrix.cc

TObject.h does not include TBuffer.h anymore.
(see https://root.cern.ch/doc/v608/release-notes.html#core-libraries)
Added include of TBuffer.h in complexMatrix.cc

partialWaveFit: compatibility with ROOT 6.08

---

storageFormats/eventFileWriter.h

Finally understood the second issue with ROOT 6.08 observed by @fkaspar and @cdreisbach. If also BAT is to be used, then an additional declaration of `TClonesArray` is required to compile the event file writer.

Another fix for ROOT 6.08

---

pyInterface/bindings/decayAmplitude/ampIntegralMatrixMetadata_py.cc
pyInterface/module/_integrals.py

When using more amplitude files for calculating the integrals, the
keyfile content was added n-files times, which created a warning. 
Now, the keyfile content is added only once and checked for any further
amplitude file.

Remove warning when using more amplitude files for calculating the integrals

---

CMakeLists.txt
README.md
cmakeModules/FindNumPy.cmake

And a Cmake module to search for 'numpy'. 'numpy' is required for a couple of Python scripts, so it should be a hard requirement to be able to build ROOTPWA.

Require 'numpy'

---

partialWaveFit/fitResult.cc

Reduce the number of warnings printed while filling a 'rpwa::fitResult'
object with empty covariance, normalization or acceptance integrals. In
that case only warn once (about an empty matrix) instead of (in case of
the covariance matrix) complain for each production amplitude.

partialWaveFit: less warnings for fit result without matrices

---

CMakeLists.txt
cmakeModules/FindROOT.cmake
resonanceFit/CMakeLists.txt
resonanceFit/massDepFitComponents.cc
resonanceFit/massDepFitComponents.h
resonanceFit/massDepFitFunction.cc

Require C++11 while configuring ROOTPWA. Do not yet actually modify any code (apart from removing non-C++11 workarounds).

Require C++11

---

pyInterface/bindings/decayAmplitude/ampIntegralMatrixMetadata_py.cc
pyInterface/bindings/utilities/reportingUtilsEnvironment_py.cc
pyInterface/module/_integrals.py

Set the hash to a value if all amplitude files have the same hash, and this hash is the same as the current ROOTPWA hash. Otherwise leave it empty (as is currently the case).

Set git hash in ampIntegralMatrixMetadata

---

particleData/particleDataTable2016.txt

Update the particle data table to the values from the 2016 edition of
the PDG.

particleData: update to PDG 2016 values

---

pyInterface/module/_config.py

When on-the-fly bins are generated from a range and a number of bins, now the bin borders are rounded to 14 significant digites to get rid of the nummeric effects of the boundary calculation. (e.g. 2.4000000000000004)

Implement rounding to 14 significant digits for on-the-fly binning

---

partialWaveFit/pwaLikelihood.cc
partialWaveFit/pwaLikelihood.h

The 'pwaLikelihood<complexT>::_debug' variable needs to be
instantiated to be accessible from '...::setQuiet'. The variable is
only declared in the header file, so move the function definiation to
the implementation file. (-Wundefined-var-template)
Appears to be a new check in Apple LLVM version 8.1.0.

partialWaveFit: fix compiler warning for non-instantiated variable

---

.travis.yml

Now (https://github.com/travis-ci/travis-ci/issues/4681) all elements of
the build matrix need to be explicitely specified.
*sigh*

buildSystem: follow travis changes for build matrix

---

pyInterface/bindings/decayAmplitude/ampIntegralMatrix_py.cc
pyInterface/bindings/highLevelInterface/pwaFit_py.cc
pyInterface/bindings/highLevelInterface/pwaNloptFit_py.cc
pyInterface/bindings/partialWaveFit/fitResult_py.cc
pyInterface/bindings/partialWaveFit/pwaLikelihood_py.cc
pyInterface/bindings/pyUtils/stlContainers_py.cc
pyInterface/bindings/pyUtils/stlContainers_py.h
pyInterface/bindings/storageFormats/eventFileWriter_py.cc
pyInterface/bindings/storageFormats/eventMetadata_py.cc

Implement a converter functions between Python and C++ for the
multibinBoundariesType.
Replace the multiple implementations of this conversion by the common
converter functions.

pyInterface: Implement Python converter for multibinBoundariesType

---

generators/diffractivePhaseSpace.cc
generators/generatorManager.cc
generators/generatorPickerFunctions.cc
generators/generatorPickerFunctions.h

Implement a picker that picks the mass and t' uniformly in the given
range. This allows, e.g. to generate events with a fixed mass and t'.

generators: Implement 'uniformMassAndT' picker and special treatment of t' = 0

---

pyInterface/module/pyPartialWaveFit/_startParameterGenerator.py

Make proper use of numpy random state. By using 'self.generator'
instead of 'np.random' the provided seed get respected.

startParameterGenerator: fix usage of random state
