ROOTPWA-Maintainers/ROOTPWA

- src/CMakeLists.txt
- src/calcCovMatrixForFitResult.cc
create an executable that opens an existing fit result file and calculates the
analytical covariance matrix for this fit result. It adds the covariance matrix
to the fit result object and saves the new fit result as a new file.
> src: create executable that adds covariance matrix to fit result file

- decayAmplitude/ampIntegralMatrix.cc
- decayAmplitude/test/particleDataTable.txt
- doc/tex/likelihood.tex
- nlopt/pwaNloptFit.cc
- partialWaveFit/CMakeLists.txt
- partialWaveFit/addIntegralsToFitResult.cc
- partialWaveFit/calcCovMatrixForFitResult.cc
- partialWaveFit/compareFitResultsIntegrals.cc
- partialWaveFit/eigenvectorLikelihoodSlices.cc
- partialWaveFit/fitResult.cc
- partialWaveFit/fitResult.h
- partialWaveFit/likelihoodPointCalculator.cc
- partialWaveFit/partialWaveFitHelper.cc
- partialWaveFit/partialWaveFitHelper.h
- partialWaveFit/pwaLikelihood.cc
- partialWaveFit/pwaLikelihood.h
- partialWaveFit/pwafit.cc
- partialWaveFit/stripIntegralsFromFitResult.cc
- partialWaveFit/test/testLikelihood.cc
- resonanceFit/massDepFitFunction.cc
- utilities/conversionUtils.hpp
Mostly cosmetics, the most important non-cosmetic changes are:
* updated the documentation to include the formulas for the second derivatives
* the analytic Hessian and covariance matrix respect fixed parameters
* small fixes for ranks other than 1
* try to extract for information from the fit result, and reduce number of command line arguments for a couple of tools.
> Small corrections of _v2 import

- src/rootscripts/plotGui.C
Improve the plotGui script by making it update the result plots whenever the selection in the list is changed and by revising the layout of the result plots.
> Improve plotGui.C.

- src/rootscripts/plotGui.C
Make plotting of several fit results over each other possible in the plotGui script and clean it up a little bit.
> Allow for multiple results in the plotGui script.

- CMakeLists.txt
- amplitude/ampIntegralMatrix.cc
- amplitude/decayTopology.cc
- amplitude/evtTreeHelper.cc
- amplitude/evtTreeHelper.h
- amplitude/fsVertex.cc
- amplitude/isobarDecayVertex.cc
- amplitude/particle.cc
- amplitude/test/testAmplitude.cc
- amplitude/test/testAmplitudeTree.cc
- amplitude/test/testDecayTopology.cc
- amplitude/test/testIntegral.cc
- amplitude/test/testIsospinSym.cc
- amplitude/test/testParticle.cc
- amplitude/test/testPeakShapeInstableIsobar.cc
- amplitude/test/testWaveDescription.cc
- amplitude/test/testWaveSetGenerator.cc
- amplitude/waveDescription.cc
- src/fitResult.cc
- src/massDepFit.cc
- src/massDepFitComponents.h
- src/massDepFitFsmd.cc
- tools/addisokey.cc
- tools/key2tex.cc
- utilities/test/testArray.cc
- utilities/test/testFileUtils.cc
- utilities/test/testSpinUtils.cc
- utilities/test/testSumAccumulators.cc
Change ROOTPWA's default build type to "RELWITHDEBINFO", add the possibility to compile with -Wextra and fix the compilation with that.
> Make ROOTPWA compile with -Wextra and change default build type.

- partialWaveFit/fitResult.cc
- partialWaveFit/fitResult.h
Add a getter for the fit parameter error by name to the fit result.
> src: Add getter for fit parameter error.

- relativisticAmpCorrections/TFracNum.h
- resonanceFit/massDepFit.cc
- resonanceFit/massDepFitComponents.cc
- resonanceFit/massDepFitComponents.h
- resonanceFit/massDepFitFsmd.cc
- resonanceFit/massDepFitFsmd.h
- resonanceFit/massDepFitMinimizer.h
- resonanceFit/massDepFitMinimizerRoot.cc
- resonanceFit/massDepFitMinimizerRoot.h
- resonanceFit/pwaMassFit.cc
* add a constant background parametrisation to the resonance fit
* correct some types of variables in relativisticAmpCorrections and resonanceFit
* cosmetics: better names of minimizer parameter names for FSMD, ...
> Various fixes and constant background for resonance fit

- pyInterface/decayAmplitude/phaseSpaceIntegral_py.cc
- pyInterface/utilities/physUtils_py.cc
Fix some bugs and add some functions in the pyInterface.
> Fix minor things in pyInterface.

- partialWaveFit/pwaLikelihood.cc
- partialWaveFit/pwaLikelihood.h
improved the memory structure of the pwaLikelihood to account for
different numbers of positive and negative reflectivity waves
> improve memory structure for pwaLikelihood.cc

- pyInterface/genPseudoData.py
make genPseudoData generate events of the type "real" instead of "generated".
> pyInterface: make genPseudoData generate eventsType "real"

- README.md
- decayAmplitude/massDependence.cc
update instructions for Boost and yaml-cpp; remove references to
SourceForge; update instructions for ROOTPWA tags and branches
> docs: update and extend README

- utilities/libConfigUtils.hpp
the signature setting[std::string] was removed; fix code to use
setting[const char*] instead; tested to work with V1.4.9
> libconfig: fix compilation error with V1.5.0

- relativisticAmpCorrections/CMakeLists.txt
- relativisticAmpCorrections/TFracNum.cc
- relativisticAmpCorrections/TFracNum.h
- relativisticAmpCorrections/TLSContrib.cc
- relativisticAmpCorrections/TLSContrib.h
Several older commits which I found laying around which should improve things in general.
> relampl: Fix several things.

- cmakeModules/FindYamlCpp.cmake
Try to get a version for YamlCpp from the pkgconfig file installed by
the library.
> buildSystem: get version for YamlCpp

- decayAmplitude/waveDescription.cc
- highLevelInterface/pwaNloptFit.cc
* Import some rather important fix to the Nlopt partial-wave fit by Oliver
* some cosmetics (whitespaces) in waveDescription.cc`
> Fix Nlopt fit

- highLevelInterface/calcAmplitude.cc
- pyInterface/package/_fileManager.py
- pyInterface/package/amplitude.py
- pyInterface/package/integrals.py
- pyInterface/userInterface/calcIntegrals.py
Fix several smaller problems with return values, error messages and root
functions used.
> Fix several smaller problems.

- nBodyPhaseSpace/randomNumberGenerator.cc
- nBodyPhaseSpace/randomNumberGenerator.h
- partialWaveFit/fitResult.cc
- partialWaveFit/fitResult.h
- pyInterface/package/fit.py
- pyInterface/partialWaveFit/fitResult_py.cc
- pyInterface/partialWaveFit/pwaLikelihood_py.cc
- pyInterface/userInterface/pwaFit.py
- pyInterface/userInterface/pwaNloptFit.py
Add the possibility to do multiple fit attempts with one call to pwa(Nlopt)Fit.py. On the way, collect several cosmetic changes and improvements and one rather fatal bug fix, which are all included in this pull request.
> Add possibility for multiple fit attempts in one go.

- pyInterface/package/utils/__init__.py
- pyInterface/package/utils/_fitTreeUtils.py
Add two functions to the utilities which should make it easier to handle large
numbers of fit results in TTrees.
> pyInterface: Add some utility functions.

- pyInterface/userInterface/eigenvectorLikelihoodSlices.py
Improve the eigenvectorLikelihoodSlices script by adding an option telling the
script not to calculate the Hessian analytically (because it was already
calculated that way when the fit result file was produced). Also fix a problem
with the python version of the '*' operator.
> pyInterface: Improve eigenvectorLikelihoodSlices.

- generators/diffractivePhaseSpace.cc
- generators/generator.h
- pyInterface/generators/generator_py.cc
- pyInterface/genpw.py
+ Implements access to the mass and t' value of the generated event
in the generator function.
+ Implements saving of mass and t' in the event files when calling
genpw.py
> generators: Add saving of mass and t' in genpw.py script

- partialWaveFit/complexMatrix.cc
Fix compilation of `complexMatrix` with the latest version of Apple's Xcode.
> Fix compilation with latest Xcode

- pyInterface/plotAngles.py
Fix the angle plotting script by making use of the metadata and removing the
old logic of finding input files. Instead, the input files have to be given
explicitly. This is an intermediate step, as this script should be transformed
into a function in the pyRootPwa package and then called with a new script
using the file manager to figure out where the input files are.
> Fix angle plotting script.

- decayAmplitude/ampIntegralMatrixMetadata.cc
- decayAmplitude/ampIntegralMatrixMetadata.h
- pyInterface/decayAmplitude/ampIntegralMatrixMetadata_py.cc
- pyInterface/pyUtils/rootConverters_py.cc
Fix two issues when compiling with '-Wextra'.
> Fix compilation issues with '-Wextra'.

- pyInterface/bindings/decayAmplitude/ampIntegralMatrixMetadata_py.cc
- pyInterface/module/_likelihood.py
- pyInterface/module/utils/_waveDescThresUtils.py
- pyInterface/scripts/calcCovMatrixForFitResult.py
- pyInterface/scripts/eigenvectorLikelihoodSlices.py
- pyInterface/scripts/likelihoodPointCalculator.py
* Fix likelihood initialization of #164
* Fix name of function in python interface
> Important fixes

- storageFormats/eventMetadata.cc
Fix two bugs in the merging of event files.
> Fix merging of event data

- README.md
Add a section explaining the installation of NLopt and BAT.
Closes #142 .
> Documentation: update README

- .travis.yml
- test/testMC.sh
- travisCI/install-bat.sh
- travisCI/install-boost.sh
- travisCI/install-cmake.sh
- travisCI/install-libconfig.sh
- travisCI/install-root.sh
- travisCI/install-yaml-cpp.sh
> Travis update

- CMakeLists.txt
- decayAmplitude/massDependence.cc
- pyInterface/bindings/generators/generatorPickerFunctions_py.cc
- pyInterface/module/_fileManager.py
- pyInterface/scripts/calcAmplitudes.py
- pyInterface/scripts/convertTreeToEvt.py
- pyInterface/scripts/generatePhaseSpace.py
- pyInterface/scripts/plotAngles.py
Various fixes and improvements mainly in the Python interface.
Most important is probably the fix to make building/linking on MacOS work again.
> Fixes and improvements

- decayAmplitude/ampIntegralMatrix.cc
- pyInterface/bindings/storageFormats/eventMetadata_py.cc
- storageFormats/eventMetadata.cc
- storageFormats/eventMetadata.h
Implement additionalVariables class that handles additional
variables of an event tree.
Additionally, impelement a member function that uses these variables
to determine wether the current event is in a given multibin.
> storageFormats: additionalTreeVariables class

- decayAmplitude/massDependence.cc
- decayAmplitude/massDependence.h
- decayAmplitude/waveDescription.cc
- pyInterface/bindings/decayAmplitude/massDependence_py.cc
Implement generic GLASS parameterization from LHCb/BaBar
and K-Matrix parameterization from Palano, Pennington.
Implement possibility to handel parameters for the mass-dependent isobar
parameterization from the key file to the parameterization.
> decayAmplitude: Parameterizations for [Kpi]_S wave

- partialWaveFit/fitResult.cc
- partialWaveFit/fitResult.h
- partialWaveFit/stripIntegralsFromFitResult.cc
- pyInterface/bindings/partialWaveFit/fitResult_py.cc
- pyInterface/bindings/pyUtils/stlContainers_py.cc
- pyInterface/bindings/pyUtils/stlContainers_py.h
- pyInterface/module/utils/__init__.py
- pyInterface/module/utils/_fitTreeUtils.py
C++ implementation of getFitResultsFromFiles.
> Get fit results
